### ISSUE TITLE
How to use this in xcode project..??

### ISSUE THREAD

**Issue by cloudjanak** [wayne530/words-with-friends-solver#1]

**Comment by wayne530** [comment]
You can't use this in an xcode project. It's perl. But you should feel free to port the code over for your needs.

**Comment by cloudjanak** [comment]
First Of all a salute for this code,
and its working Fantastic and efficient.
can you convert this code in objective-c because i want to make game like this in my collage project.
almost i have created but board scanning and AI player is bit more tuff.
so if it possiable than please convert it into objective-c or php.
Thankx in Advance.
